INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (1, 'INT61', 3, 12, 'ICT-training', 'Java Advanced JPA Introduction');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3001, 'INT61', 3, 12, 'ICT-training', 'C#.NET Introduction');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3002, 'INT62', 3, 12, 'ICT-training', 'C#.NET Advanced');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3003, 'INT11', 3, 12, 'ICT-training', 'CNC-Programmatie Dialogue');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3004, 'INT04', 3, 12, 'ICT-training', 'CNC-Programmatie Advanced');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3005, 'INT65', 3, 12, 'ICT-training', 'Java Introduction');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3006, 'INT66', 3, 12, 'ICT-training', 'Java Advanced');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3007, 'INT91', 4, 12, 'ICT-training', 'Java and Hibernate');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3008, 'INT92', 2, 12, 'ICT-training', 'Java Enterprise Edition and Struts');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3009, 'BIU09', 3, 20, 'Construction', 'MS Access Introduction');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3010, 'BIU10', 2, 20, 'Construction', 'MS Access Advanced');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3011, 'BIU06', 2, 20, 'Construction', 'MS Excel Advanced');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3012, 'INT08', 2, 12, 'ICT-training', 'Objectoriented programming Introduction');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3013, 'INT84', 2, 12, 'ICT-training', 'System design');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3014, 'INT80', 2, 12, 'ICT-training', 'VB.NET Introduction');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3015, 'INT81', 2, 12, 'ICT-training', 'VB.NET Advanced');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3016, 'BIU25', 1, 20, 'Construction', 'VBA for Access');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3017, 'BIU24', 3, 20, 'Construction', 'VBA for Excel');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3018, 'INT99', 2, 12, 'ICT-training', 'Webservices in.NET');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3019, 'INT98', 3, 12, 'ICT-training', 'Windows Powershell');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3020, 'INT95', 2, 12, 'ICT-training', 'ADO.NET and XML in VB.NET');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3021, 'GRI11', 1, 20, 'Graphics', 'Adobe Flash ActionScript');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3022, 'GRI09', 3, 20, 'Graphics', 'Adobe Dreamweaver : Advanced');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3023, 'INT46', 3, 12, 'ICT-training', 'ASP.NET');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3024, 'INT68', 3, 12, 'ICT-training', 'Databases');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3025, 'INT93', 1, 12, 'ICT-training', 'Service Oriented Architecture (SOA)');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3026, 'INT27', 3, 12, 'ICT-training', 'XML');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3027, 'INF06', 4, 6, 'Sales', 'Selling total ICT-solutions');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3028, 'INF01', 1, 6, 'Sales', 'Salestechniques and -strategy in ICT - part 1');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3029, 'INF02', 3, 6, 'Sales', 'Salestechniques and -strategy in ICT - part 2');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3030, 'INF58', 2, 16, 'Sales', 'ICT customer needs and diagnosis');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3031, 'BUN47', 2, 12, 'Sales', 'Get the most out of PowerPoint for convincing (commercial) presentations');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3032, 'INT71', 1, 12, 'Communication', 'Communication for ICT-project managers');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3033, 'INF12', 1, 16, 'Communication', 'Goal-oriented coaching of a team of commercial ICT employees');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3034, 'INF14', 3, 12, 'Communication', 'Help desk skills');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3035, 'BIU51', 2, 12, 'Communication', 'Internet: Optimal use of Internet communication applications');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3036, 'INF80', 1, 6, 'Communication', 'Introduction to the banking world for IT professionals');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3037, 'BIU12', 3, 12, 'Communication', 'Internet and Communication - Construction');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3038, 'INF77', 1, 16, 'Communication', 'Negotiating and collaborating in ICT teams');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3039, 'BUN76', 1, 12, 'Communication', 'Creating professional e-mails via Outlook');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3040, 'INF61', 3, 8, 'Communication', 'Problem-solving conversations for the IT manager');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3041, 'GRH25', 1, 10, 'Sales', 'Sales via internet');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3042, 'VAG05', 1, 25, 'Communication', 'New trends on the internet for 45+: make sure you are up to date!');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3043, 'INF21', 1, 16, 'Communication', 'Peoplemanagement for ICT-employees');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3044, 'INF20', 4, 10, 'Communication', 'Projectmanagement for computer scientists');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3045, 'INT89', 4, 12, 'ICT-training', 'SharePoint Portal Server 2007');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3046, 'TAL48', 5, 12, 'Communication', 'Language training for call centers agents: French');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3047, 'TAL49', 5, 12, 'Communication', 'Language training for call centers agents: Dutch');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3048, 'INT05', 3, 12, 'ICT-training', 'TCP/IP');
INSERT INTO lesson.training (id, code, duration, max, theme, title) VALUES (3049, 'INT61', 3, 12, 'ICT-training', 'Java Advanced JPA Introduction');